[package]
name = "weld"
version = "0.1.0"
authors = ["Matei Zaharia <matei.zaharia@gmail.com>"]
build = "build.rs"

[dependencies]
lazy_static = "0.2.1"
regex = "0.1.71"
rustyline = "1.0.0"
easy_ll = { path = "easy_ll", version = "^0.1.0" }
libc = "0.2.0"
getopts = "0.2.14"
csv = "0.15.0"

[lib]
path = "weld/lib.rs"
crate-type = ["dylib", "rlib"]

[[bin]]
name = "repl"
path = "weld/bin/repl.rs"

[[bench]]
name = "benches"
path = "benches/driver.rs"
harness = false

[[test]]
name = "integration_tests"
harness = false
