[package]
name = "weld"
version = "0.1.0"
authors = ["Matei Zaharia <matei.zaharia@gmail.com>"]

[dependencies]
lazy_static = "0.2.1"
regex = "0.1.71"
easy_ll = { path = "easy_ll", version = "^0.1.0" }

[lib]
path = "weld/lib.rs"

[[bin]]
name = "repl"
path = "weld/bin/repl.rs"
